version: '3.8'

services:
  poa-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharos-invaders
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Монтируем директории для персистентности данных
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_lib:/var/lib/letsencrypt
      # Если нужны дополнительные статические файлы
      - ./sounds:/var/www/poa/sounds:ro
      - ./images:/var/www/poa/images:ro
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    networks:
      - poa_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poa.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.services.poa.loadbalancer.server.port=80"

  # Опциональный сервис для автоматического SSL через Traefik
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik.yml:/traefik.yml:ro
      - letsencrypt_certs:/letsencrypt
    networks:
      - poa_network
    profiles:
      - traefik  # Запускается только с профилем --profile traefik

volumes:
  nginx_logs:
  letsencrypt_certs:
  letsencrypt_lib:

networks:
  poa_network:
    driver: bridge