[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Pharos Testnet Configuration
[rpc_endpoints]
pharos_testnet = "https://testnet.dplabs-internal.com"

[etherscan]
pharos_testnet = { key = "${PHAROS_API_KEY}", url = "https://testnet-explorer.dplabs-internal.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options