const GAME_CONFIG = {
    CRAB_SPEED: 60,
    CRAB_FIRE_RATE: 66,
    CRAB_BULLET_SPEED: 87,
    
    PLAYER_LIVES: 5,
    PLAYER_SPEED: 110,
    PLAYER_FIRE_RATE: 130,
    PLAYER_BULLET_SPEED: 115,
    
    LEVEL_DIFFICULTY: 83,
    SCORE_MULTIPLIER: 100,
    WAVE_SPEED_INCREASE: 5,
    
    GAME_FEE: '0.001',
    
    PARTICLE_COUNT: 88,
    ANIMATION_SPEED: 100,
    
    INVADERS_ROWS: 5,
    INVADERS_COLS: 10,
    
    BULLET_PENETRATION: false,
    DOUBLE_SHOT: false,
    SHIELD_MODE: false,
};

console.log('🎮 Game config loaded:', GAME_CONFIG);
