# Traefik статическая конфигурация
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Точки входа
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Провайдеры
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: poa_network

# Сертификаты Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com  # Замените на ваш email
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# API и Dashboard
api:
  dashboard: true
  insecure: true  # Только для разработки, в продакшене использовать HTTPS

# Логи
log:
  level: INFO

accessLog: {}